package com.iapppay.channel.pack.v1.util;

import com.iapppay.channel.pack.v1.config.Config;

import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Point;

import javax.swing.JPanel;

/**
 * @author Administrator
 */
public class WaitDialog extends javax.swing.JDialog {

    private static final long serialVersionUID = 1L;

    public WaitDialog(Component parentComponent, String message) {
        initComponents(parentComponent, message);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents(Component parentComponent, String message) {
        jPanel1 = new JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        setAlwaysOnTop(true);
        setUndecorated(true);

        jLabel2.setText(message);
        jLabel2.setIcon(new javax.swing.ImageIcon(WaitDialog.class.getResource(
                "wait.gif")));
        jPanel1.add(jLabel1, BorderLayout.WEST);
        jPanel1.add(jLabel2, BorderLayout.EAST);
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(
                0,
                0,
                0)));
        getContentPane().add(jPanel1);

        setSize(Config.WAIT_DIALOG_WIDTH, Config.WAIT_DIALOG_HEIGHT);
        Point point = parentComponent.getParent().getLocationOnScreen();
        int height = parentComponent.getHeight();//height如果被替代成Constants.TOOL_HEIGHT有误差。width也是
        int width = parentComponent.getWidth();
        setLocation((width - Config.WAIT_DIALOG_WIDTH) / 2 + point.x, (height - Config.WAIT_DIALOG_HEIGHT) / 2 + point.y);
        //        setLocationRelativeTo(parentComponent.getParent());
        // pack();
    }

    public void setMessage(String msg) {
        jLabel2.setText(msg);
    }

    public void setWidth(int width) {
        setSize(width, 50);
    }

    //    /**
    //     * @param args
    //     *            the command line arguments
    //     */
    //    public static void main(String args[])
    //    {
    ////        java.awt.EventQueue.invokeLater(new Runnable() {
    ////            public void run()
    ////            {
    //                new WaitDialog("").setVisible(true);
    ////            }
    ////        });
    //    }

    // Variables declaration - do not modify
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private JPanel jPanel1;
    // End of variables declaration

}
